runtime: php55
entrypoint: "php -S 0.0.0.0:8080 -t api"
api_version: 1
handlers:
  - url: /.*
    script: auto
  # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$
    application_readable: true
  # Serve php scripts.
  - url: /(.+\.php)$
    script: \1